### ISSUE TITLE
Feature request: use TypeScript to only check for number types

### ISSUE THREAD

**Issue by binary64** [shuckster/eslint-plugin-big-number-rules#1]
string one = "hi"
string two = "there"
if (one === two) {
  console.log("test")
}

shows "is this a financial calculation?"

but with TypeScript it would know they are strings.

I love this rule but when a rule is noisy, I find people just mentally block it all out entirely

**Comment by shuckster** [comment]
Thank you for this. I've been intending on addressing things that are clearly "non financial ops" for a while.

The approach would have to be a little more than just checking for strings though, since when using a BigNumber library it's important to work with strings as much as possible to [avoid IEEE-754 errors](https://github.com/shuckster/eslint-plugin-big-number-rules#but-why). I ought to update the README to make this clear, also. Always pass strings into BigNumber!

Anyway, a consequence of this is that the example you presented should be fixable for both TypeScript and JavaScript by inspecting the string-literals and checking for obvious signs that they're representing numbers. It'll be a little more difficult for dynamic calculations, but there's clearly some low-hanging fruit that can get rid of quite a few of the more "noisy" warnings!

Incidentally, check out the [importDeclaration](https://github.com/shuckster/eslint-plugin-big-number-rules/wiki/Limit-the-number-of-warnings) config. It might help you limit the warnings only to particular files that you've designated for doing financial calculations.

**Comment by binary64** [comment]
Hmm, what if we expected these big number strings to be "instanceof BigNumber" instead? Like in C# you would do `is Decimal` so I'm wondering if we could treat this similar. Then we wont have to ultimately deal with a lot of noise coming from number/string types.

**Comment by shuckster** [comment]
> Hmm, what if we expected these big number strings to be "instanceof BigNumber" instead?

If you're using TypeScript you could probably solve this with your own "shim" that interfaces directly with BigNumber. Something like:

```ts
class LargeNumber {
  sum(...numbers: BigNumber[]) {
    return BigNumber.sum(...numbers);
  }
}
```

Then, you could tweak your eslint config:

```json
    "big-number-rules": {
      "importDeclaration": "large-number-shim.js",
      "importSpecifier": "LargeNumber",
      "construct": "LargeNumber"
    }
```

However, for dealing with your OP example for both TypeScript and JavaScript we need to do more work:

```js
let one = "hi"
let two = "there"
if (one === two) {
  console.log("test")
}
```

The plugin needs to test for `BigNumber(one/two/etc...).isNaN()` before running the rule to see if the string actually represents a number.

For the following case this is relatively easy:

```js
if ("hi" === "there") {
  console.log("test")
}
```

I think this could be added without much complexity.

However, for variables like `one` and `two` the plugin needs to first evaluate them, which requires more work to parse. Also, if the variables do not resolve to a string within the same file the plugin would still have to show a warning, since I don't think we can inspect the contents of imports.

Anyway, the "easy" case above is on my list of things to try first and should hopefully get rid of a few warnings.

**Comment by shuckster** [comment]
Updated the [Wiki documentation](https://github.com/shuckster/eslint-plugin-big-number-rules/wiki/Limit-the-number-of-warnings#typescript) based on the above.

**Comment by shuckster** [comment]
Just wanted to come back here and mention that `Object.is` can circumvent usage of `===` for comparisons that don't relate to big-numbers:

```js
let one = "hi"
let two = "there"
if (Object.is(one, two)) {
  console.log("test")
}
```

This is now pointed-out in the documentation linked above.

**Comment by shuckster** [comment]
Version 2.0.0 of the plugin [will now suggest](https://github.com/shuckster/eslint-plugin-big-number-rules#but-i-use--for-string-concatenation) an `Object.is` alternative for equality operators.

Also, `String#concat()` and `Template String` replacements are also [now offered](https://github.com/shuckster/eslint-plugin-big-number-rules#but-i-use--for-string-concatenation) for `+` related rules.

**Comment by shuckster** [comment]
@binary64 + cc: @luke-underwood

The original post should now be ignored by the plugin since version 2.2.0:

```js
let one = "hi";
let two = "there";
if (one === two) {
  console.log("test");
}
```

The condition will no longer show an "is this a financial calculation?" warning.

Additionally, the plugin now supports inspection of variables, objects, and arrays, and *will* show a warning for the following addition:

```js
const arr = [{ val: "1" }, { val: ["2"] }];
let val = arr[0].val + arr[1].val[0];
// ^ is this a financial calculation?
```

This only works if the values resolve to literals in the current scope, but it's an improvement.
